# This is the OpenAPI implementation of the plone.restapi endpoints for
# plone.app.contenttypes.interfaces.IDocument and
# Products.ATContentTypes.interfaces.IATDocument objects and complements the
# main file at plonesiteroot.yaml
swagger: '2.0'

info:
  version: "1.0a10"
  title: Plone Rest API - Document content type
  description: |
    A hypermedia API, with the portal root as the entry point. The client can ask for a REST API response by setting the 'Accept' HTTP header to 'application/json'. These are the definitions of the ``Document`` content type endpoints.

host: localhost:8080
consumes:
  - application/json
produces:
  - application/json

basePath: /Plone

################################################################################
#                                  Security                                    #
################################################################################
# Next is valid only for OpenAPI 3.0
# securityScheme:
#   Authorization:
#     type: http
#     scheme: bearer
#     bearerFormat: JWT

# Describe your paths here
paths:
  /{document_object}:
    get:
      x-for:
        - plone.app.contenttypes.interfaces.IDocument
        - Products.ATContentTypes.interfaces.IATDocument
      description: |
        Gets a Document content type.
      parameters:
        -
          name: document_object
          in: path
          description: The Document content type id.
          required: true
          type: string
        -
          name: payload
          in: body
          description: The endpoint body payload
          schema:
            $ref: '#/definitions/PloneObject'

        - $ref: '#/parameters/AcceptHeader'
        - $ref: '#/parameters/AuthorizationBearerHeader'

      responses:
        200:
          description: Successful response [TODO Needs schema object]

    patch:
      x-for:
        - plone.app.contenttypes.interfaces.IDocument
        - Products.ATContentTypes.interfaces.IATDocument
      description: |
        Changes a document content type.
      parameters:
        -
          name: document_object
          in: path
          description: The Document content type id.
          required: true
          type: string
        -
          name: payload
          in: body
          description: The endpoint body payload
          schema:
            $ref: '#/definitions/PloneObject'

        - $ref: '#/parameters/AcceptHeader'
        - $ref: '#/parameters/AuthorizationBearerHeader'

      responses:
        200:
          description: Successful response object created [TODO Needs schema object]

    delete:
      x-for:
        - plone.app.contenttypes.interfaces.IDocument
        - Products.ATContentTypes.interfaces.IATDocument
      description: |
        Deletes a document content type.
      parameters:
        -
          name: document_object
          in: path
          description: The Document content type id.
          required: true
          type: string

        - $ref: '#/parameters/AcceptHeader'
        - $ref: '#/parameters/AuthorizationBearerHeader'

      responses:
        204:
          description: Empty response

  /{document_path}/@workflow:
    get:
      x-for:
        - Products.CMFCore.interfaces.IFolderish
      description: |
        Get the workflow of a "folderish" object.
          It's defined for the interfaces:
          - Products.CMFCore.interfaces.IFolderish
      parameters:
        -
          name: document_path
          in: path
          description: ID of the object to fetch
          required: true
          type: string

        - $ref: '#/parameters/AcceptHeader'

      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/ContentWorkflowObject'

  /{document_path}/@workflow/{transition}:
    get:
      x-for:
        - Products.CMFCore.interfaces.IFolderish
      description: |
        Get the workflow of a "folderish" object.
          It's defined for the interfaces:
          - Products.CMFCore.interfaces.IFolderish
      parameters:
        -
          name: document_path
          in: path
          description: ID of the object to fetch
          required: true
          type: string
        -
          name: transition
          in: path
          description: ID of the transition to trigger
          required: true
          type: string

        - $ref: '#/parameters/AcceptHeader'

      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/ContentWorkflowHistoryObject'

################################################################################
#                                 Parameters                                   #
################################################################################
parameters:
  AuthorizationBearerHeader:
    name: Authorization
    in: header
    description: |
      The JWT Authorization Bearer header in the form of ``Authorization: Bearer <JWT_TOKEN>``
    required: true
    type: string
    format: string

  AcceptHeader:
    name: Accept
    in: header
    description: Accept header
    required: true
    type: string
    format: string
    default: application/json


################################################################################
#                                 Definitions                                  #
################################################################################
definitions:
  PloneObject:
    type: object
    required:
      - "@type"
    properties:
      "@id":
         type: string
      "@type":
        type: string
      title:
        type: string
      description:
        type: string

  ContentWorkflowHistoryObject:
    type: object
    properties:
      action:
        type: string
      actor:
        type: string
      comments:
        type: string
      review_state:
        type: string
      time:
        type: string
        format: date

  ContentWorkflowTransitionsObject:
    type: array
    items:
      type: object
      properties:
        "@id":
          type: string
        title:
          type: string

  ContentWorkflowObject:
    type: object
    properties:
      history:
        type: array
        items:
          $ref: '#/definitions/ContentWorkflowHistoryObject'
      transitions:
        type: array
        items:
          $ref: '#/definitions/ContentWorkflowTransitionsObject'
